/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import core.Person;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Thor
 */
public class OperatorPanelOnline extends panels.JAPanel {

    cso.JALabel posTF = new cso.JALabel("oPos", "");
    cso.JALabel sekTF = new cso.JALabel("oSek", "");
    Person op;

    public OperatorPanelOnline(Person op) {
        this.removeAll();
        this.add(posTF);
        this.add(sekTF);
        posTF.setVisible(false);
        sekTF.setVisible(false);
        this.op = op;
        initComponents();

        oMETATF.setText(op.getSek() + " " + op.getPos());
        posTF.setText(op.getPos());
        sekTF.setText(op.getSek());
        System.out.println(op.getSek());
        //posTF.setText(op.getPos());
        System.out.println(op.getPos());
        firstNameTF.setText(op.getFirstName() + " " + op.getSurName());

        System.out.println(op.getFirstName());
        mailTF.setText(op.getMail());
        System.out.println(op.getMail());
        phoneTF.setText(op.getTel());
        System.out.println(op.getTel());

    }

    /**
     * Creates new form LogedInPanel
     */
    public OperatorPanelOnline() {
        op = new Person();
        initComponents();
    }

    public Person getOperator() {
        return op;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mailTF = new cso.JALabel("oMail","");
        phoneTF = new cso.JALabel("oPhone", "");
        jLabel2 = new javax.swing.JLabel();
        firstNameTF = new cso.JALabel("oName", "");
        oMETATF = new cso.JALabel("oMETA", "");

        setMaximumSize(new java.awt.Dimension(400, 93));
        setMinimumSize(new java.awt.Dimension(400, 93));

        jLabel2.setText("Inloggad som");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oMETATF, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oMETATF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameTF;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel mailTF;
    private javax.swing.JLabel oMETATF;
    private javax.swing.JLabel phoneTF;
    // End of variables declaration//GEN-END:variables
}
