/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import core.Person;
import cso.JALabel;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JLabel;

/**
 *
 * @author Thor
 */
public class OperatorPanelOnlineRemake extends panels.JAPanel {

    Person op;

    public OperatorPanelOnlineRemake(Person op) {
        this.removeAll();
        this.op = op;
        initComponents();

    }

    /**
     * Creates new form LogedInPanel
     */
    public OperatorPanelOnlineRemake() {
        op = new Person();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        this.removeAll();
        JALabel nameTF = new cso.JALabel("oName", "");
        JALabel sekTF = new cso.JALabel("oSek", "");
        JALabel mailTF = new cso.JALabel("oMail", "");
        JALabel phoneTF = new cso.JALabel("oPhone", "");
        jLabel2 = new javax.swing.JLabel();
        JALabel posTF = new cso.JALabel("oFunc", "");
        sekTF.setText(op.getSek());
        System.out.println(op.getSek());
        posTF.setText(op.getPos());
        System.out.println(op.getPos());
        nameTF.setText(op.getFirstName());
        System.out.println(op.getFirstName());
        mailTF.setText(op.getMail());
        System.out.println(op.getMail());
        phoneTF.setText(op.getTel());
        System.out.println(op.getTel());
        setMaximumSize(new java.awt.Dimension(400, 93));
        setMinimumSize(new java.awt.Dimension(400, 93));

        jLabel2.setText("Inloggad som");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(sekTF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(posTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(posTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sekTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
        );
    }// </editor-fold>                        

    /**
     *
     * @return list of all values in following order, Name, EMail, Phone,
     * Sektion, Function.
     */
    public ArrayList<String> getValues() {
        ArrayList<String> ret = new ArrayList(
                Arrays.asList("#oName#" + nameTF.getText(), "#oMail#" + mailTF.getText(), "#oTel#" + phoneTF.getText(), "#oPos#" + sekTF.getText().split(" (")[0], "oFunc" + sekTF.getText().split(" (")[1].replace(")", "")));
        return ret;
    }
    // Variables declaration - do not modify                     
    private JLabel jLabel2;
    public JALabel mailTF;
    private JALabel nameTF;
    private JALabel phoneTF;
    private JALabel posTF;
    private JALabel sekTF;
    // End of variables declaration                   
}
